### ISSUE TITLE
Can I use Zlib 1.2.8 ?

### ISSUE THREAD

**Issue by adriansyah** [tidwall/DeflateSwift#1]
Hi,

Thanks for the library. I just wondering I could use zlib 1.2.8 instead of 1.2.5. If so, where can i change the config for that ?

Cheers

**Comment by tidwall** [comment]
Xcode only includes support up to 1.2.5. So you'll need to compile from the zlib source. Once you have a 1.2.8 dylib built for your platform (iOS or OS X), remove the previous "libz.dylib" and include the new one by clicking the "Add Other..." button.

![image](https://cloud.githubusercontent.com/assets/1156077/11213371/e2937a52-8cf8-11e5-9f5c-c713f42dd4ea.png)

Hope this helps and thanks for using the project.
